export const styles = {
  container: {
    height: "100dvh",
    minHeight: "100dvh",
    overflowY: "auto",
    WebkitOverflowScrolling: "touch",
    background: "#000",
    color: "#fff",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', 'Segoe UI', Roboto, sans-serif",
    position: "relative",
  },
  topBar: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "max(14px, env(safe-area-inset-top, 0px) + 10px) 16px 12px",
    background: "rgba(0,0,0,0.92)",
    backdropFilter: "blur(20px)",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  title: { fontSize: "18px", fontWeight: 700, margin: 0, flex: 1 },
  search: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    margin: "12px 16px",
    padding: "11px 12px",
    borderRadius: "14px",
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    color: "#fff",
    fontSize: "16px",
  },
  catHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "22px 16px 8px",
    color: "#fff",
    fontSize: "17px",
    fontWeight: 700,
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "10px 16px",
  },
  thumb: { width: "48px", height: "48px", borderRadius: "12px", objectFit: "cover", flexShrink: 0, background: "rgba(255,255,255,0.08)" },
  rowName: { fontSize: "15px", margin: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  pricePill: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    marginTop: "4px",
    padding: "3px 9px",
    borderRadius: "9px",
    background: "rgba(255,255,255,0.08)",
    border: "none",
    color: "#fff",
    fontSize: "13px",
    cursor: "pointer",
  },
  toggle: { width: "44px", height: "26px", borderRadius: "13px", padding: "3px", border: "none", cursor: "pointer", flexShrink: 0 },
  toggleKnob: { display: "block", width: "20px", height: "20px", borderRadius: "50%", background: "#fff", transition: "transform 0.2s ease" },
  addBtn: {
    width: "calc(100% - 32px)",
    margin: "8px 16px 18px",
    minHeight: "48px",
    borderRadius: "14px",
    border: "1px dashed rgba(255,255,255,0.18)",
    background: "transparent",
    color: "rgba(255,255,255,0.6)",
    fontSize: "15px",
    cursor: "pointer",
  },
  sheetBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "flex-end",
    zIndex: 50,
  },
  sheet: {
    width: "100%",
    maxHeight: "90%",
    overflowY: "auto",
    background: "#161618",
    borderTopLeftRadius: "22px",
    borderTopRightRadius: "22px",
    padding: "12px 18px calc(28px + env(safe-area-inset-bottom, 0px))",
  },
  grabber: { width: "36px", height: "4px", borderRadius: "2px", background: "rgba(255,255,255,0.25)", margin: "0 auto 14px" },
  label: { display: "block", fontSize: "12px", fontWeight: 600, color: "rgba(255,255,255,0.7)", textTransform: "uppercase", letterSpacing: "0.5px", margin: "14px 0 6px" },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "14px 14px",
    borderRadius: "14px",
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.05)",
    color: "#fff",
    fontSize: "16px",
    outline: "none",
  },
  primaryBtn: { width: "100%", boxSizing: "border-box", minHeight: "48px", borderRadius: "14px", border: "none", background: "#fff", color: "#000", fontSize: "15px", fontWeight: 700, cursor: "pointer" },
  dangerBtn: { width: "100%", minHeight: "48px", borderRadius: "14px", border: "1px solid rgba(239,68,68,0.32)", background: "rgba(239,68,68,0.08)", color: "#f87171", fontSize: "15px", fontWeight: 600, cursor: "pointer", marginTop: "14px" },
  chip: { fontSize: "12px", display: "inline-flex", alignItems: "center", gap: "4px" },
  toast: {
    position: "fixed",
    left: "16px",
    right: "16px",
    bottom: "calc(20px + env(safe-area-inset-bottom, 0px))",
    padding: "12px 16px",
    borderRadius: "14px",
    background: "#1f1f22",
    color: "#fff",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 60,
  },
  galleryStrip: { display: "flex", gap: "10px", overflowX: "auto", WebkitOverflowScrolling: "touch", padding: "2px 0 10px", marginBottom: "4px" },
  galleryItem: (isCover) => ({ position: "relative", width: "88px", height: "88px", flexShrink: 0, borderRadius: "12px", boxShadow: isCover ? "0 0 0 2px #fff" : "none" }),
  galleryThumb: { display: "block", width: "88px", height: "88px", borderRadius: "12px", backgroundColor: "rgba(255,255,255,0.06)", backgroundSize: "cover", backgroundPosition: "center" },
  coverBadge: { position: "absolute", bottom: "4px", left: "4px", background: "rgba(0,0,0,0.62)", color: "#fff", fontSize: "9px", fontWeight: 600, padding: "2px 6px", borderRadius: "6px", letterSpacing: "0.3px" },
  coverBtn: { position: "absolute", bottom: "4px", left: "4px", width: "30px", height: "30px", borderRadius: "50%", border: "none", background: "rgba(0,0,0,0.55)", color: "#fff", fontSize: "15px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
  removeBtn: { position: "absolute", top: "4px", right: "4px", minWidth: "28px", height: "28px", borderRadius: "14px", border: "none", background: "rgba(220,38,38,0.9)", color: "#fff", fontSize: "13px", fontWeight: 700, padding: "0 8px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
  removeBtnConfirm: { position: "absolute", top: "4px", right: "4px", height: "28px", borderRadius: "14px", border: "none", background: "rgba(220,38,38,1)", color: "#fff", fontSize: "11px", fontWeight: 700, padding: "0 10px", cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", whiteSpace: "nowrap" },
  addTile: { width: "88px", height: "88px", flexShrink: 0, borderRadius: "12px", border: "1px dashed rgba(255,255,255,0.25)", background: "transparent", color: "rgba(255,255,255,0.6)", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", position: "relative" },
};
